// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Racing
{
	[System.Serializable]
	public class WheelInfo
	{
		public float tireWear;
		private IRDSWheel _wheelRef;
		public WheelInfo (IRDSWheel aWheel)
		{
			_wheelRef = aWheel;
			_wheelRef.SetWear(true);
			_wheelRef.realTireMode = true;

		}

		public void Update() {
			
		//	_wheelRef.SetWear(true);
			tireWear = _wheelRef.GetTyreWear();
		//	Debug.Log(tireWear+" - "+_wheelRef.realTireMode+" - "+this._wheelRef.GetTyreTemp());

		//	Debug.Log ("Pause here");
		}
	}
}

