// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using Drivers;
using Cars;


namespace Teams
{
	[System.Serializable]
	public class GTTeamBase
	{
		
		public List<GTDriver> drivers = new List<GTDriver>();
		public List<GTCar> cars = new List<GTCar>();
		public Color teamColor;
		public Color wheelColor;
		public bool humanControlled = false;
		public string teamName;
		public int seasonPoints = 0;
		public int seasonWins = 0;
		public int cash = 200000;
		public static string HUMANS_DEBUG_TEAM = "Test Pilots";
		
		public int reputation;

		public GTTeamBase ()
		{

		}
		public bool addResearchToTeam(GTEquippedResearch aResearch) {
			bool r = false;
			bool car1 = cars[0].forceAddPartToCar(aResearch);
			bool car2 = cars[1].forceAddPartToCar(aResearch);
			return car1||car2;
		}
	}
}

