// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Drivers;
using System.Collections.Generic;
using UnityEngine;


namespace Teams
{
	public class GTTeamWithDrivers : GTTeamBase
	{
		public List<DriverRelationshipRecord> driverRelationships = new List<DriverRelationshipRecord>();
		public GTTeamWithDrivers ()
		{
		}


		public void initDriverRelationships() {
			for(int i = 0;i<GTDriver.allDrivers.Count;i++) {
				driverRelationships.Add(new DriverRelationshipRecord(GTDriver.allDrivers[i],this.reputation));
			}
		}

		public DriverRelationshipRecord relationshipWithDriver(GTDriver aDriver) {
			for(int i = 0;i<driverRelationships.Count;i++) {
				Debug.Log(driverRelationships[i].record.name+" - "+aDriver.name);
				if(driverRelationships[i].record==aDriver) {
					return driverRelationships[i]; 
				}
			}
			return null;
		}
		public void addDriverPoints(int aPosition) {
			for(int i = 0;i<this.driverRelationships.Count;i++) {
				float differenceToDemand = (float) driverRelationships[i].record.positionDemanded- (float) aPosition;
				// If positive, we have impressed this sponsor
				// If Negative, we have lost reputation with this sponsor;
				if(differenceToDemand<-8) {
					differenceToDemand = -8;
				} 
				if(differenceToDemand>8) {
					differenceToDemand = 8;
				}
				// Multiply by 20 to make it more effective
				for(int j = 0;j<this.drivers.Count;j++) {
					differenceToDemand *= drivers[j].sponsorFriendliness;
				}
				differenceToDemand *= 10;
				driverRelationships[i].currentRelationshipValue += Convert.ToInt32(differenceToDemand);
				if(driverRelationships[i].currentRelationshipValue<0) { 
					driverRelationships[i].currentRelationshipValue = 0;
				}
				if(driverRelationships[i].currentRelationshipValue>1000) {
					driverRelationships[i].currentRelationshipValue = 1000;
				}
				
			}
		}

		public void initDriver(GTDriver aDriver) {
			this.drivers.Add(aDriver);
			aDriver.contract.team = (GTTeam) this;
			aDriver.contract.remainingOnContract = 1;
		}
	}
}

