// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
using Drivers;
using Cars;
using Utils;
using Database;


namespace Teams
{
	[System.Serializable]
	public class GTTeamBase
	{
		
		public bool ignoreFromRelegationAndPromotion = false;
		public List<GTDriver> drivers = new List<GTDriver>();
		public List<GTCar> cars = new List<GTCar>();
		public Color teamColor;
		public Color wheelColor;
		public bool humanControlled = false;
		public string teamName;
		public int seasonPoints = 0;
		public int seasonWins = 0;
		public int cash = 200000;
		public static string HUMANS_DEBUG_TEAM = "Test Pilots";
		public int id = 0;
		public int reputation;

		public GTTeamBase ()
		{

		}
		public virtual void FromString(string aString) {
			string uncom = Base64.Base64Decode(aString);
			string[] s = uncom.Split(new char[] {'|'});
			GTDriver d = new GTDriver();
			d.FromString(s[0]);

			this.drivers.Add(d);
			d = new GTDriver();
			d.FromString(s[1]);
			this.drivers.Add(d);
			GTCar c = new GTCar();
			c.FromString(s[2]);
			this.cars.Add(c);
			c = new GTCar();
			c.FromString(s[3]);
			this.cars.Add(c);

			teamColor.r = (float) Convert.ToDouble(s[4]);
			teamColor.g = (float) Convert.ToDouble(s[5]);
			teamColor.b = (float) Convert.ToDouble(s[6]);
			teamColor.a = 1f;
			wheelColor.r = (float) Convert.ToDouble(s[7]);
			wheelColor.g = (float) Convert.ToDouble(s[8]);
			wheelColor.b = (float) Convert.ToDouble(s[9]);
			wheelColor.a = 1f;

			if(s[10].ToLower()=="true") {
				humanControlled = true;
			} else {
				humanControlled = false;
			}
			this.teamName = s[11];
			this.seasonPoints = Convert.ToInt32(s[12]);
			this.seasonWins =Convert.ToInt32(s[13]);
			this.cash = Convert.ToInt32(s[14]);
			this.reputation = Convert.ToInt32(s[15]);
			this.id = Convert.ToInt32(s[16]);

			DriverLibraryRecord rec = DriverLibrary.REF.driverByID(drivers[0].id);
			
			rec.assignedTeam = id;
			rec = DriverLibrary.REF.driverByID(drivers[1].id);
			 
			rec.assignedTeam = id; 

			ignoreFromRelegationAndPromotion = false;
		}
		public virtual string SaveString() {
			string s = drivers[0].SaveString()+"|"+drivers[1].SaveString()+"|"+cars[0].SaveString()+"|"+cars[1].SaveString()+"|"+
			teamColor.r+"|"+teamColor.g+"|"+teamColor.b+"|"+wheelColor.r+"|"+wheelColor.g+"|"+wheelColor.b+"|"+
			humanControlled+"|"+teamName+"|"+seasonPoints+"|"+seasonWins+"|"+cash+"|"+reputation+"|"+this.id;
			return Base64.Base64Encode(s);

		}  
		public bool addResearchToTeam(GTEquippedResearch aResearch) {
			bool r = false;
			bool car1 = cars[0].forceAddPartToCar(aResearch);
			bool car2 = cars[1].forceAddPartToCar(aResearch);
			return car1||car2;
		}
	}
}

