// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class DriverInterestInfo
{
	public string driverInterestString;
	public float payDemand;
	public float willAccept;
	public int contractLength;
	public float bonusDemand;
	public DriverInterestInfo (string aInterestString,float aValue,float aWillAcceptAmount,int aContractLengthOffer,float aBonusValue)
	{
		driverInterestString = aInterestString;
		payDemand = aValue;
		willAccept = aWillAcceptAmount;
		contractLength = aContractLengthOffer;
		bonusDemand = aBonusValue;
	}
}


