// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Teams;
using championship;


namespace Drivers
{
	public class DriverContract
	{	
		public int payPerRace;
		public int remainingOnContract;
		public int bonusPerRace;
		public GTTeam team;
		public DriverContract ()
		{
		}

		public int compensationAmount {
			get {
				int compensationAmount = (ChampionshipSeason.ACTIVE_SEASON.racesRemainingInSeason*payPerRace)+(remainingOnContract+(payPerRace*5));
				return compensationAmount;
			}
		}
	}
}

