// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Cars;
using Database;
using UnityEngine;
using System.Collections.Generic;


namespace Drivers
{
	[System.Serializable]
	public class GTDriver : GTDriverBase
	{
		public GTCar assignedCar;
		public int championshipPoints;
		public int lastRacePoints;

		public static List<GTDriver> allDrivers = new List<GTDriver>();
		public GTDriver ()
		{
		}



	
	}
}

