// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Utils;
using System.Collections.Generic;
using championship;


namespace MenuScene
{
	public class NewGameOrLoadBtn : MonoBehaviour
	{
		public UILabel gameLabel;
		public UIButton deleteButton;
		public UIButton gameButton;
		
		public int thisIndex;
		public NewGameMaker gameMaker;

		public NewGameOrLoadBtn ()
		{
		}
	
		public void OnEnable() {
			if(SaveGameUtils.HasSavedGameAtIndex(thisIndex)) {
				string headline = SaveGameUtils.headlineGameInfo(thisIndex);
				this.gameLabel.text = headline;
				this.deleteButton.gameObject.SetActive(true);
			} else {
				
				this.deleteButton.gameObject.SetActive(false);
			}
		}
		public void onClicked() {
			
			SaveGameUtils.USING_INDEX = thisIndex;
			if(SaveGameUtils.HasSavedGameAtIndex(thisIndex)) {
				Debug.Log ("Load Game");
				List<string> l = ES2.LoadList<string>(SaveGameUtils.SAVED_GAME_NAME+thisIndex);
				
				ChampionshipSeason champ = GameObject.Find ("ChampionshipObject").GetComponent<ChampionshipSeason>();
				champ.FromString(l[(int) ESavedGameSetup.GameData]);
				champ.season = Convert.ToInt32(l[(int) ESavedGameSetup.SeasonsPast]);
				Application.LoadLevel("Garage");
			} else {
				Debug.Log ("New Game");
				MainMenuScene.REF.doGameMaker(thisIndex);
			}
		}
	}
} 

