// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using championship;


namespace MenuScene
{
	public class NewGameMaker : MonoBehaviour
	{
		public UIInput teamName;
		public NewGameMaker ()
		{
		}

		public void onStartGame() {
			teamName.value = teamName.value.Replace("|","");
			teamName.value = teamName.value.Replace("%","");
			if(teamName.value=="") {
				teamName.value = "Test Pilots";
			}
			ChampionshipSeason champ = GameObject.Find ("ChampionshipObject").GetComponent<ChampionshipSeason>();
			champ.initFromDatabase(teamName.value);
		}
	}
}

