// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Database;
using GoogleFu;

	public class SponsorScreen : MonoBehaviour
	{
	public UILabel companyTitle;
	
	public int showingSponsor = 0;
	public UI2DSprite companySprite;
	 
		public SponsorScreen ()
		{
		 
		}

		private UILabel initLabel(string aSearch) {
		GameObject g = GameObject.Find(aSearch);
			if(g!=null) {
				return g.GetComponent<UILabel>();
			} 
		return null;
		}

		public void Start() {
			if(SponsorDatabase.REF!=null)
			showSponsor(SponsorDatabase.REF.sponsorByID(1));
		}
		public void initLabels() {
			UI2DSprite[] uis = this.GetComponentsInChildren<UI2DSprite>();
			for(int i = 0;i<uis.Length;i++) {
				if(uis[i].name=="LogoSprite") {
					this.companySprite = uis[i];
				}
			}
			companyTitle = initLabel("SponsorTitle");
		}
		public void showNextSponsor() {
			showingSponsor++; 
			if(showingSponsor>=SponsorDatabase.REF.sponsors.Count) {
				showingSponsor = 0;
			}
			showSponsor(SponsorDatabase.REF.sponsors[showingSponsor]);
			
		}
		public void showPreviousSponsor() {
			showingSponsor--;
			if(showingSponsor<0){
				showingSponsor = SponsorDatabase.REF.sponsors.Count-1;
			}
			showSponsor(SponsorDatabase.REF.sponsors[showingSponsor]);
		}
		public void showSponsor(SponsorRecord aSponsor) {
			if(companyTitle==null) {
				initLabels();
			} 
			showingSponsor = SponsorDatabase.REF.indexOfSponsor(aSponsor);
			companySprite.sprite2D = aSponsor.logo;
			companyTitle.text = aSponsor.name;
		}
	}


