// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class SponsorInterestInfo
{
	public string sponsorInterestString;
	public float sponsorValue;
	public int contractLength;
	
	public SponsorInterestInfo (string aInterestString,float aValue,int aContractLengthOffer)
	{
		sponsorInterestString = aInterestString;
		sponsorValue = aValue;
		contractLength = aContractLengthOffer;
	}
}


