// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using GoogleFu;
using System.Collections.Generic;

namespace Database
{
	public class CarDatabase : MonoBehaviour
	{
		public List<CarLibraryRecord> cars = new List<CarLibraryRecord>();
		public static CarDatabase REF;
		public CarDatabase ()
		{

		}

		public void Start() {

		}
		public void init() {
			DontDestroyOnLoad (this.gameObject);
			REF = this;
			List<CarLibraryRow> carLibRows = CarLibrary.Instance.Rows;
			for(int i = 0;i<carLibRows.Count;i++) {
				cars.Add(new CarLibraryRecord(carLibRows[i]));
			}

		}
		public CarLibraryRecord carByName(string aName) {
			for (int i = 0; i<cars.Count; i++) {
				if(cars[i].name==aName) {
					return cars[i];
				}
			}
			return cars [0];
		}

		public IRDSCarControllerAI carByID(int aID) {
			for (int i  = 0; i<cars.Count; i++) {
				if(cars[i].id==aID) {
					return cars[i].carPrefab.GetComponent<IRDSCarControllerAI>();
				}
			}
			return cars [0].carPrefab.GetComponent<IRDSCarControllerAI>();
		}
	}
}

