// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GoogleFu;
using UnityEngine;


namespace Database
{
	[System.Serializable]
	public class CarLibraryRecord
	{
		public int id;
		public string name;
		public int carCost;
		public int carStyle;
		public string prefabName;
		public int maxNitro;
		public int leagueRequired;

		public float carHP;
		public float carHPRPM;

		public float carTorque;
		public float carTorqueRPM;

		public float carShiftSpeed;
		public float carAero;

		public float carFrontWing;
		public float carRearWing;

		public float carTireWearEffect;
		public float carDrivabilityEffect;

		public float carDrag;
		
		public float tireGrip;
		public float turboPSI = 0f;
		public float carMaxSpeed;

		public int frontBrakeTorque;
		public int rearBrakeTorque;
		public CarLibraryRecord (CarLibraryRow aRow)
		{
			id = aRow._id;
			name = aRow._carname;
			carCost = Convert.ToInt32(aRow._carcost);
			carStyle = aRow._carstyle;
			prefabName = aRow._carprefabname;

			carHP = aRow._carhp;
			carHPRPM = aRow._carhprpm;

			carTorque = aRow._cartorquenm;
			carTorqueRPM = aRow._cartorquerpm;

			carShiftSpeed = aRow._carshiftspeed;
			carAero = aRow._caraero;

			carFrontWing = aRow._carfrontwing;
			carRearWing = aRow._carrearwing;

			carTireWearEffect = aRow._cartireweareffect;
			carDrivabilityEffect = aRow._cardrivabilityeffect;

			carDrag = aRow._cardrag;
			this.carShiftSpeed = aRow._carshiftspeed;
			carMaxSpeed = aRow._maxspeed;
			tireGrip = aRow._tiregrip;
			leagueRequired = aRow._leaguerequired; 
		
			this.frontBrakeTorque = aRow._frontbraketorque;
			this.rearBrakeTorque = aRow._rearbraketorque;
		}  
		public string carDragString {
			get {
				if(carDrag>0.8f) {
					return "Very Poor";
				}
				if(carDrag>0.7f) {
					return "Poor";
				}
				if(carDrag>0.4f) {
					return "Average";
				}
				if(carDrag>0.3f) {
					return "Good";
				}
				if(carDrag>0.2f) {
					return "Excellent";
				}
				return "Amazing";
			}	
		}

		public GameObject carPrefab {
			get {
			//	prefabName = "GolfWhite";
				return (GameObject) Resources.Load("Cars/"+prefabName);
			}
		}
	}
} 

