// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GoogleFu;
using UnityEngine;


namespace Database
{
	[System.Serializable]
	public class CarLibraryRecord
	{
		public int id;
		public string name;
		public int carCost;
		public int carStyle;
		public string prefabName;
		public int maxNitro;

		public float carHP;
		public float carHPRPM;

		public float carTorque;
		public float carTorqueRPM;

		public float carShiftSpeed;
		public float carAero;

		public float carFrontWing;
		public float carRearWing;

		public float carTireWearEffect;
		public float carDrivabilityEffect;


		public CarLibraryRecord (CarLibraryRow aRow)
		{
			id = aRow._id;
			name = aRow._carname;
			carCost = Convert.ToInt32(aRow._carcost);
			carStyle = aRow._carstyle;
			prefabName = aRow._carprefabname;

			carHP = aRow._carhp;
			carHPRPM = aRow._carhprpm;

			carTorque = aRow._cartorquenm;
			carTorqueRPM = aRow._cartorquerpm;

			carShiftSpeed = aRow._carshiftspeed;
			carAero = aRow._caraero;

			carFrontWing = aRow._carfrontwing;
			carRearWing = aRow._carrearwing;

			carTireWearEffect = aRow._cartireweareffect;
			carDrivabilityEffect = aRow._cardrivabilityeffect;

		}

		public GameObject carPrefab {
			get {
			//	prefabName = "GolfWhite";
				return (GameObject) Resources.Load("Cars/"+prefabName);
			}
		}
	}
}

