// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GoogleFu;
using System.Collections.Generic;
using UnityEngine;

namespace Database
{
	public class DriverLibrary : MonoBehaviour
	{		
		public List<DriverLibraryRecord> drivers = new List<DriverLibraryRecord>();
		public static DriverLibrary REF;
		public DriverLibrary ()
		{

		}
		public void Start() {
			REF = this;
		}

		public void init() {
			REF = this;
			List<DriverNamesRow> driverList = DriverNames.Instance.Rows;
			for(int i =0;i<driverList.Count;i++) {
				drivers.Add(new DriverLibraryRecord(driverList[i]));
			}
		}

		public DriverLibraryRecord driverByID(int aID) {
			for(int i = 0;i<drivers.Count;i++) {
				if(drivers[i].id==aID) {
					return drivers[i];
				}
			}
			return null;
		}
		public DriverLibraryRecord getAvailableDriver() {
			for(int i = 0;i<drivers.Count;i++) {
				if(drivers[i].assignedTeam==0) {
					return drivers[i];
				}
			} 
			return null;
		}
		public List<DriverLibraryRecord> getAllAvailableDrivers() {
			List<DriverLibraryRecord> r = new List<DriverLibraryRecord>();
			for(int i = 0;i<drivers.Count;i++) {
				if(drivers[i].assignedTeam==0) {
					r.Add(drivers[i]);
				}
			} 
			return r;
		}
	}
}

