// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GoogleFu;
namespace Database
{
	
	[System.Serializable]
	public class DriverLibraryRecord
	{
		public int assignedTeam = 0;
		public string driverName;
		public float aggressivenessOnBrake;
		public float speedSteeringFactor;
		public float lookAheadFactor;
		public float lookAheadConstant;
		public float corneringSpeedFactor;
		public float maxDriftAngle;
		public float driftingThrottleFactor;
		public float steeringDriftFactor;
		public float sideAvoidingFactor;
		public float collisionSideFactor;
		public float overtakeFactor;
		public float humanError;
		public float overtakeSpeedDifference;
		public float overtakeOffsetIncrementMin;
		public float overtakeOffsetIncrementMax;
		public float backToLineIncrement;
		public float shiftFactor;
		public float shiftUpFactor;
		public float tyreChangePercentage;
		public float fuelLoadPercentage;
		public float fullAccelMargin;
		public float frontCollDist;
		public float backCollDist;
		public float sideMargin;
		public float heightMargin;
		public float lengthMargin;
		public float SIDE_MARGIN;
		public float offtrackThrottleMultiplier;
		public float jumpThrottleMultiplier;
		public float jumpThrottleTime;
		public float agressiveMultiplier;
		public DriverLibraryRecord (DriverNamesRow aRow)
		{
			driverName = aRow._drivername;
			aggressivenessOnBrake = aRow._aggressivenessonbrake;
			speedSteeringFactor = aRow._spdsteeringfactor;
			lookAheadFactor = aRow._lookaheadfactor;
			lookAheadConstant = aRow._lookaheadconstant;
			corneringSpeedFactor = aRow._corneringspeedfactor;
			maxDriftAngle = aRow._maxdriftangle;
			driftingThrottleFactor = aRow._driftingthrotlefactor;
			steeringDriftFactor = aRow._steeringdriftfactor;
			sideAvoidingFactor = aRow._sideavoidingfactor;
			collisionSideFactor = aRow._collisionsidefactor;
			overtakeFactor = aRow._overtakefactor;
			humanError = aRow._humanerror;
			overtakeSpeedDifference = aRow._overtakespeeddifference;
			overtakeOffsetIncrementMax = aRow._overtakeoffsetincrementmax;
			overtakeOffsetIncrementMin = aRow._overtakeoffsetincrementmin;
			backToLineIncrement = aRow._backtolineincrement;
			shiftFactor = aRow._shiftfactor;
			shiftUpFactor = aRow._shiftupfactor;
			tyreChangePercentage = aRow._tyrechangepercentage;
			fuelLoadPercentage = aRow._fuelloadpercentage;
			fullAccelMargin = aRow._fullaccelmaring;
			frontCollDist = aRow._frontcolldist;
			backCollDist = aRow._backcolldist;
			sideMargin = aRow._sidemargin;
			heightMargin = aRow._heightmargin;
			lengthMargin = aRow._lengthmargin;
			SIDE_MARGIN = aRow._sidemargin_2;
			offtrackThrottleMultiplier = aRow._offtrackthrottlemultiplier;
			jumpThrottleMultiplier = aRow._jumpthrottlemultiplier;
			jumpThrottleTime = aRow._jumpthrottletime;
			speedSteeringFactor = 10000f;

			/*
			 * SIDE_MARGIN	OffTrackThrottleMultiplier	JumpThrottleMultiplier	JumpThrottleTime	AggressiveMultiplier	PassiveMultiplier
			 */
		}
	}
}

