// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Database;

public class SponsorRelationshipRecord
{
	public SponsorRecord record;
	public int currentRelationshipValue;
	public SponsorRelationshipRecord (SponsorRecord aRecord,int aRelationshipValue)
	{
		record = aRecord;
		currentRelationshipValue = aRelationshipValue - record.requiredReputation;
	}
	
	public SponsorInterestInfo interest {
		get {
			if(currentRelationshipValue<-200) {
				return new SponsorInterestInfo("Not Interested",0f,0);
			}
			if(currentRelationshipValue<-100) {
				return new SponsorInterestInfo("Becoming Interested",0f,0);
			}
			if(currentRelationshipValue<-50) {
				if(currentRelationshipValue<-75)
					return new SponsorInterestInfo("Semi-Interested",record.startPayPerRace*0.25f,4); else {
						return new SponsorInterestInfo("Semi-Interested",record.startPayPerRace*0.25f,8);
				} 
			}	
			if(currentRelationshipValue<-25) {
				if(currentRelationshipValue<-50)
					return new SponsorInterestInfo("Semi-Interested",record.startPayPerRace*0.5f,4); else {
						return new SponsorInterestInfo("Semi-Interested",record.startPayPerRace*0.5f,8);
				}
			}
			if(currentRelationshipValue<25) {
				if(currentRelationshipValue<0)
					return new SponsorInterestInfo("Interested",record.startPayPerRace,4); else {
						return new SponsorInterestInfo("Interested",record.startPayPerRace,8);
				}
			}
			if(currentRelationshipValue<100) {
				if(currentRelationshipValue<50)
					return new SponsorInterestInfo("Interested",record.startPayPerRace*1.25f,4); else {
						return new SponsorInterestInfo("Interested",record.startPayPerRace*1.25f,8);
				}
			}
			return new SponsorInterestInfo("Very Keen",record.startPayPerRace*1.5f,8);
			
			
		}
	}
}

