// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Database;

	public class SponsorPlacedRelationshipRecord : SponsorRelationshipRecord
	{
		public ESponsorPosition position;
		public int remaining = 0;
		public float valuePerRace;
		public SponsorPlacedRelationshipRecord (ESponsorPosition aSponsor,SponsorRecord aRecord,float aValuePerRace,int aRacesRemaining) : base(aRecord,0)
		{
		
			position = aSponsor;
			remaining = aRacesRemaining;
			valuePerRace = aValuePerRace;
			
		}
		public SponsorPlacedRelationshipRecord(string aPosition,int aSponsorID,float aValue,int aRemaining,int aCurrentRelationshipValue) {
			switch(aPosition) {
				default:position = ESponsorPosition.Back;break;
				case("Roof"):position = ESponsorPosition.Roof;break;
				case("Left"):position = ESponsorPosition.Left;break;
				case("Right"):position = ESponsorPosition.Right;break;
				case("Back"):position = ESponsorPosition.Back;break;
				case("Bonnet"):position = ESponsorPosition.Bonnet;break;
			}
			for(int i = 0;i<SponsorDatabase.REF.sponsors.Count;i++) {
				if(SponsorDatabase.REF.sponsors[i].id==aSponsorID) {
					this.record = SponsorDatabase.REF.sponsors[i];
					break;
				}
			}
			this.valuePerRace = aValue;
			this.remaining = aRemaining;
			this.currentRelationshipValue = aCurrentRelationshipValue;
			init(record,currentRelationshipValue);
		}
	}

