// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using GoogleFu;
using System.Collections.Generic;

namespace Database
{
	public class SponsorDatabase : MonoBehaviour
	{
		public List<SponsorRecord> sponsors = new List<SponsorRecord>();
		public static SponsorDatabase REF;
		public SponsorDatabase ()
		{
			
		}
		
		public void Start() {
			
		}
		public void init() {
			DontDestroyOnLoad (this.gameObject);
			REF = this;
			List<SponsorLibraryRow> sponsorLibRows = SponsorLibrary.Instance.Rows;
			for(int i = 0;i<sponsorLibRows.Count;i++) {
				sponsors.Add(new SponsorRecord(sponsorLibRows[i]));
			}
			
		}
		public SponsorRecord sponsorByName(string aName) {
			for (int i = 0; i<sponsors.Count; i++) {
				if(sponsors[i].name==aName) {
					return sponsors[i];
				}
			}
			return sponsors[0];
		}
		public int indexOfSponsor(SponsorRecord aRecord) {
			for (int i  = 0; i<sponsors.Count; i++) {
				if(sponsors[i]==aRecord) {
					return i;
				}
			}
			return -1;
		}
		public SponsorRecord sponsorByID(int aID) {
			for (int i  = 0; i<sponsors.Count; i++) {
				if(sponsors[i].id==aID) {
					return sponsors[i];
				}
			}
			return sponsors [0];
		}
	}
}


