// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using GoogleFu;
using System.Collections.Generic;

namespace Database
{
	public class TeamDatabase : MonoBehaviour
	{
		public List<TeamDataRecord> teams = new List<TeamDataRecord>();
		public static TeamDatabase REF;
		public TeamDatabase ()
		{
			
		}

		public void Start() {

		}

		public void init() {
			REF = this;
			while(this.teams.Count>0) {
				teams.RemoveAt(0);
			}
			List<DriverLibraryRecord> availableDrivers = DriverLibrary.REF.drivers;
			for(int i = 0;i<availableDrivers.Count;i++) {
				availableDrivers[i].assignedTeam = 0;
			}

			List<TeamNamesRow> teamLibRows = TeamNames.Instance.Rows;
			for(int i = 0;i<teamLibRows.Count;i++) {
				teams.Add(new TeamDataRecord(teamLibRows[i]));
			}
		}
		public TeamDataRecord teamFromDriverID(int aDriverID) {
			for(int i = 0;i<teams.Count;i++) {
				if(teams[i].driverA.id==aDriverID||teams[i].driverB.id==aDriverID) {
					return teams[i];
				}
			}
			return null;
		}
		public TeamDataRecord teamFromDriverName(string aDriverName) {
			for(int i =0 ;i<teams.Count;i++) {
				if(teams[i].driverA.name==aDriverName||teams[i].driverB.name==aDriverName) {
					return teams[i];
				}
			}
			return null;
		}

	}
}

