// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GoogleFu;


namespace Database
{
	[System.Serializable]
	public class TrackDatabaseRecord
	{
		public string name;
		public string sceneName;
		public string imagePrefabName;

		public TrackDatabaseRecord (RaceTracksRow aRow)
		{
			name = aRow._trackname;
			sceneName = aRow._scenename;
			imagePrefabName = aRow._texturename;
		}
	}
}

