// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

using GoogleFu;
namespace Database
{
	public class TrackDatabase : MonoBehaviour
	{
		public List<TrackDatabaseRecord> tracks = new List<TrackDatabaseRecord>();
		public static TrackDatabase REF;
		public TrackDatabase ()
		{
		}

		public void init() {
			DontDestroyOnLoad (this.gameObject);
			REF = this;
			List<RaceTracksRow> trackLibRows = RaceTracks.Instance.Rows;
			for(int i = 0;i<trackLibRows.Count;i++) {
				tracks.Add(new TrackDatabaseRecord(trackLibRows[i]));
			}
			
		}

		public TrackDatabaseRecord recordFromName(string aName) {
			for(int i = 0;i<tracks.Count;i++) {
				if(tracks[i].name==aName||tracks[i].sceneName==aName) {
					return tracks[i];
				}
			}
			return null;
		}
	}
}

