// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace championship
{
	public class ChampionshipSeasonWithRaces : ChampionshipSeasonBase
	{
		public ChampionshipRaceSettings nextRace;
		public float drsTime = 2f;
		public ChampionshipSeasonWithRaces ()
		{
		}

		public override void Update() {

			base.Update ();
			if(nextRace.startDate==this.secondsPast&&this.secondsPast>0&&allowTimeToPass) {
				allowTimeToPass = false;
				ChampionshipRaceSettings.ACTIVE_RACE = nextRace;
				StartCoroutine(LoadLevel(nextRace.track.sceneName));
			}
		}
	}
}

