// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Drivers;
using UnityEngine;
using Database;
using GoogleFu;
using System.Collections.Generic;
using Teams;
using championship;


namespace Cars
{
	[System.Serializable]
	public class GTCar
	{
		public int libraryIndex = 0;
		public CarLibraryRecord carLibRecord;

		public List<GTEquippedResearch> rndParts = new List<GTEquippedResearch>();
		public GTCar (CarLibraryRecord aRecord)
		{

		}
		public GTCar(string aCarName)
		{
			carLibRecord = CarDatabase.REF.carByName (aCarName);
		}

		public GTEquippedResearch hasResearchCompletingOnDay(int aDay) {
			for(int i = 0;i<rndParts.Count;i++) {
				if(rndParts[i].dayOfCompletion==aDay) {
					return rndParts[i];
				}
			}
			return null;

		}
		public void replaceCar(CarLibraryRecord aCar) {
			carLibRecord = aCar;
		}
		public GTEquippedResearch partBeingResearched {
			get {
				for(int i = 0;i<rndParts.Count;i++) {
					if(rndParts[i].daysOfResearchRemaining>0) {
						return rndParts[i];
					}
				}
				return null;
			}
		}
		public int nitroCapacity {
			get {
				int c = 0;
				for(int i = 0;i<rndParts.Count;i++) {
					c += rndParts[i].researchRow._effectonnitrocapacity*rndParts[i].level;
				}
				return c;
			}
		}
		public bool hasDRS {
			get {
				return false;
			}
		}
		public float nitroStrength {
			get {
				float c = 0f;
				for(int i = 0;i<rndParts.Count;i++) {
					c += rndParts[i].researchRow._effectonnitrodurability*rndParts[i].level;
				}
				return c;
			}
		}
		public float nitroFuel {
			get {
				float c = 0f;
				for(int i = 0;i<rndParts.Count;i++) {
					c += rndParts[i].researchRow._effectonnitrofuel*rndParts[i].level;
				}
				return c;
			}
		}
			
		public void initRandomResearch(int aCount) {
			int i = 0;
			while(i<aCount) {
			//	RnDRow part = RnD.Instance.Rows[UnityEngine.Random.Range(0,RnD.Instance.Rows.Count)];
			//	addPartToCar(part,ChampionshipSeason.ACTIVE_SEASON.getTeamFromCar(this));
				RnDRow part = RnD.Instance.Rows[10];
				addPartToCar(part,ChampionshipSeason.ACTIVE_SEASON.getTeamFromCar(this));


				i++;
			} 
		}

		public void applyResearchToCar(IRDSDrivetrain aDriveTrain,IRDSCarControllerAI aAI,RacingAI aRacingAI) {
			for(int i = 0;i<this.rndParts.Count;i++) {
				rndParts[i].applyPartToCar(aDriveTrain,aAI,aRacingAI);
			}
		}
		public GTEquippedResearch hasPart(RnDRow aRow) {

			for(int j=0;j<rndParts.Count;j++) {
				if(rndParts[j].researchRow==aRow&&rndParts[j].level>0) {
					return rndParts[j];
				}
			}

			return null;
		}
		public bool hasPreRequisiteParts(string aPrerequisites) {
			if(aPrerequisites==null||aPrerequisites.Length==0) {
				return true;
			}
			string[] split = aPrerequisites.Split(new char[] {','});
			for(int i = 0;i<split.Length;i++) {
				for(int j=0;j<rndParts.Count;j++) {
					if(rndParts[j].researchRow._partname==split[i]) {
						return true;
					}
				}
			} 
			return false;
		}

		public GTEquippedResearch addPartToCar(RnDRow aRow,GTTeam aTeam) {
		//	if(aRow._par
			for(int i = 0;i<rndParts.Count;i++) {
				if(this.hasPreRequisiteParts(aRow._partprerequisites)) {
					if(rndParts[i].researchRow==aRow) {
						if(rndParts[i].level<aRow._maxlevelstounlock) {
							rndParts[i].level++;
							return rndParts[i];
						} else {
							return null;
						}
					}
				}
			}
			if(this.hasPreRequisiteParts(aRow._partprerequisites)) {
				rndParts.Add(new GTEquippedResearch(aRow));
				return rndParts[rndParts.Count-1];
			} else {
				return null;
			}
		}
		public IRDSCarControllerAI carReference {
			get {
				return carLibRecord.carPrefab.GetComponent<IRDSCarControllerAI>();
			}
		}

	}
}

