// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using Drivers;
using championship;
using Teams;
using Cars;


public class NewDriverPanel : DriverPanel
{
	public List<GTDriver> driverList = new List<GTDriver>();
	public int currentIndex;
	public GTDriver thisDriver;
	public DriverPanel myDriverPanel;
	public NewDriverPanel ()
	{
	}

	public void Start() {
		
		Lean.LeanTouch.OnFingerSwipe += OnFingerSwipe;
		List<GTDriver> availableDrivers = new List<GTDriver>();
		List<GTDriver> allDrivers = GTDriver.allDrivers;
		GTTeam team = ChampionshipSeason.ACTIVE_SEASON.getUsersTeam();
		for(int i = 0;i<allDrivers.Count;i++) {
			if(ChampionshipSeason.ACTIVE_SEASON.getTeamFromDriver(allDrivers[i])!=team) {
				availableDrivers.Add(allDrivers[i]);
			}
		}
		driverList = availableDrivers;
		this.initDriver(availableDrivers[0]);
		
		GarageManager.REF.doConversation("OpenHireDriverScreen");
	}

	public void OnDestroy() {
		
		Lean.LeanTouch.OnFingerSwipe -= OnFingerSwipe;
	}

	public void hireThisDriver() {

		GarageManager.REF.doConversation("OpenHireDriversScreen");
		GTTeam team = ChampionshipSeason.ACTIVE_SEASON.getUsersTeam();
		GTCar car = team.getGTCarFromDriver(myDriverPanel.driverRef);
		int indexForMyDriver = team.indexForDriver(this.myDriverPanel.driverRef);
		
		GTDriver oldDriver = this.myDriverPanel.driverRef;
		GTDriver newDriver = driverList[currentIndex];
		GTTeam oldTeam = ChampionshipSeason.ACTIVE_SEASON.getTeamFromDriver(newDriver);
		int indexForOldDriver = oldTeam.indexForDriver(newDriver);
		oldTeam.drivers[indexForOldDriver] = myDriverPanel.driverRef;
		team.drivers[indexForMyDriver] = newDriver;
		this.myDriverPanel.initDriver(driverList[currentIndex]);
		this.myDriverPanel.showButtons();
		Destroy(this.gameObject);
	
	}
	public void OnFingerSwipe(Lean.LeanFinger finger)
	{
		
		// Store the swipe delta in a temp variable
		var swipe = finger.SwipeDelta;
		
		if (swipe.x < -Mathf.Abs(swipe.y))
		{
			Debug.Log ("You swiped left!");
		}
		
		if (swipe.x > Mathf.Abs(swipe.y))
		{
			Debug.Log ("You swiped right!");
		}
		
		if (swipe.y < -Mathf.Abs(swipe.x))
		{
			Debug.Log ("You swiped down!");
			showDriver(currentIndex+1);
		}
		
		if (swipe.y > Mathf.Abs(swipe.x))
		{
			Debug.Log ("You swiped up!");
			showDriver(currentIndex-1);
		}
		
	}
	public void showDriver(int aIndex) {
		if(aIndex>=driverList.Count) {
			aIndex = 0;
		}
		if(aIndex<0) {
			aIndex = driverList.Count-1;
		}
		this.currentIndex = aIndex;
		this.initDriver(driverList[aIndex]);
	}
	public void alignToLeft() {
		
		
		GameObject go = this.transform.FindChild("DriverBuyFadeBG").gameObject;
		UISprite spr = go.GetComponent<UISprite>();
		if(spr!=null) {
			
			go = this.transform.parent.gameObject;
			
			if(go!=null) {
				Debug.Log ("Game Object is: "+go);
				Transform t = go.transform;
				//	pan.leftAnchor.target = t;
				spr.leftAnchor.relative = 0.02f;
				//pan.rightAnchor.target = t;
				spr.rightAnchor.relative = 0.35f;
				//pan.topAnchor.target = t;
				spr.topAnchor.relative = 0.80f;
				spr.topAnchor.absolute = 0;
				
				
				spr.bottomAnchor.target = t;
		//		spr.bottomAnchor.relative = 0;
		//		spr.bottomAnchor.absolute = 0;
				spr.ResetAndUpdateAnchors();
			}
		}
	}

}

