// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace championship
{
	public enum ERandomEventType
	{
		FinishAheadOf = 1,
		ResearchLeaked = 2,
		ResearchBreakthrough = 3,
		DriverImprovement = 4,
		ExclusiveSponsorDeal = 6,
		LoseARace = 7,
		ToxicDriver = 5,
	}
}

