// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Teams;
using Database;
using Drivers;


namespace championship
{
	public class RandomEventBase
	{
		public ERandomEventType eventType;
		public GTTeam targetTeam;
		public ResearchItem researchItem;
		public int date;
		public int rewardCash;
		public GTDriver effectedDriver;
		public SponsorRecord effectedSponsor;
		public string conversation;
		public int targetDate;
		public ERaceStartEventBehaviour raceStartBehaviour;
		public string alertMessage;

		public string wonAlert;
		public string lostAlert;
		public string startConversation;
		public RandomEventBase ()
		{
		} 
	}
}

