// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Teams;
using PixelCrushers.DialogueSystem;


namespace championship
{
	public class RandomEvent : RandomEventBase
	{
		public bool acknowledged = false;
		public RandomEvent (int aDay)
		{
			this.date = aDay;
			
			GTTeam usersTeam = ChampionshipSeason.ACTIVE_SEASON.getUsersTeam();
			ChampionshipSeasonLeague division = ChampionshipSeason.ACTIVE_SEASON.leagueForTeam(usersTeam);
			switch(UnityEngine.Random.Range(1,1)) {
				case(1):this.eventType = ERandomEventType.FinishAheadOf;setupForFinishAheadOf(usersTeam,division);break;
				case(2):this.eventType = ERandomEventType.ResearchLeaked;break;
				case(3):this.eventType = ERandomEventType.ResearchBreakthrough;break;
				case(4):this.eventType = ERandomEventType.DriverImprovement;break;
				case(5):this.eventType = ERandomEventType.ExclusiveSponsorDeal;break;
				case(6):this.eventType = ERandomEventType.LoseARace;break;
			}

		}
		
		public void initLua() {
			if(targetTeam!=null) {
				DialogueLua.SetVariable("RandomEventFinishAheadOf",targetTeam.teamName);
			}
			if(this.rewardCash>0) {
				string s = rewardCash.ToString("C0");
				DialogueLua.SetVariable("RandomEventValueString",s);
			}
		}
		public void setupForFinishAheadOf(GTTeam aMyTeam,ChampionshipSeasonLeague aLeague) {
			GTTeam team = aLeague.findTeam1AboveOrBelow(aMyTeam);
			this.targetTeam = team;
			this.targetDate = ChampionshipSeason.ACTIVE_SEASON.nextRace.startDate;
			this.alertMessage = "Score more points in the race than "+team.teamName;
			raceStartBehaviour = ERaceStartEventBehaviour.Alert;
			startConversation = "RandomEventFinishAheadOf";
			rewardCash = UnityEngine.Random.Range(1000,aMyTeam.cash);
			if(rewardCash>aMyTeam.cash) {
				rewardCash = aMyTeam.cash;
			}
			rewardCash = (rewardCash/1000)*1000;
			this.wonAlert = "You scored more than "+team.teamName+" and win "+rewardCash.ToString("C0")+"!";
			this.lostAlert = "You failed to score more than "+team.teamName+" and lose "+rewardCash.ToString("C0")+"!";
		}

		public void doConversation() {
			
		}

	}
}

