// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Utils
{
	public enum ESavedGameSetup
	{
		SavedGameHeadline = 1,
		GameData =2,
		SeasonsPast = 3,
		Day = 4,
	}
}

