// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;


namespace Utils
{
	public class SetNullAnchorsToGameObject : MonoBehaviour
	{
		public string gameObject;
		public float relativeLeft;
		public float relativeRight;
		public float relativeTop;
		public float relativeBottom;
		
		public int absoluteLeft;
		public int absoluteRight;
		public int absoluteTop;
		public int absoluteBottom;
		
		
		public bool ignoreTopAnchor = false;
		public bool ignoreBottomAnchor = false;
		public bool doOnEnable = false;
		public bool reapplyAfterFirstFrame = false;
		public SetNullAnchorsToGameObject ()
		{
		
		}
		
		[ContextMenu("SetAnchorsOverride")]
		public void OnEnableOverride() {
			UIWidget widget = this.GetComponent<UIWidget>();
			if(widget!=null) {
				GameObject go = GameObject.Find(gameObject);
				if(gameObject=="Parent") {
					go = this.transform.parent.gameObject;
				}
				if(go!=null) {
					Transform t = go.transform;
						widget.leftAnchor.target = t;
						widget.leftAnchor.relative = relativeLeft;
						widget.leftAnchor.absolute = absoluteLeft;
						widget.rightAnchor.target = t;
						widget.rightAnchor.relative = relativeRight;
						widget.rightAnchor.absolute = absoluteRight;
					if(!this.ignoreTopAnchor) {
						widget.topAnchor.target = t;
						widget.topAnchor.relative = relativeTop;
						widget.topAnchor.absolute = absoluteTop;
					}
					if(!this.ignoreBottomAnchor) {
						widget.bottomAnchor.target = t;
						widget.bottomAnchor.relative = relativeBottom;
						widget.bottomAnchor.absolute = absoluteBottom;
					}
					widget.ResetAndUpdateAnchors();
				}
			} else {
				UIPanel pan = this.GetComponent<UIPanel>();
				if(pan!=null) {
					GameObject go = GameObject.Find(gameObject);
					if(gameObject=="Parent") {
						go = this.transform.parent.gameObject;
					}
					if(go!=null) {
						Debug.Log ("Game Object is: "+go);
						Transform t = go.transform;
						pan.leftAnchor.target = t;
						pan.leftAnchor.relative = relativeLeft;
						pan.leftAnchor.absolute = absoluteLeft;
						pan.rightAnchor.target = t;
						pan.rightAnchor.relative = relativeRight;
						pan.rightAnchor.absolute = absoluteRight;
						if(!this.ignoreTopAnchor) {
							pan.topAnchor.target = t;
							pan.topAnchor.relative = relativeTop;
							pan.topAnchor.absolute = absoluteTop;
							
						}
						if(!this.ignoreBottomAnchor) {
							pan.bottomAnchor.target = t;
							pan.bottomAnchor.relative = relativeBottom;
							pan.bottomAnchor.absolute = absoluteBottom;
						}
						pan.ResetAndUpdateAnchors();
					}
				}
			}
		}
		
		private IEnumerator reapply() {
			yield return new WaitForEndOfFrame();
			OnEnable();
		}
			
		[ContextMenu("SetAnchors")]
		public void OnEnable() {
			if(reapplyAfterFirstFrame) {
				StartCoroutine(reapply());
			}
			UIWidget widget = this.GetComponent<UIWidget>();
			if(widget!=null) {
				GameObject go = GameObject.Find(gameObject);
				if(go!=null) {
					Transform t = go.transform;
					if(widget.leftAnchor.target==null) {
						widget.leftAnchor.target = t;
						widget.leftAnchor.relative = relativeLeft;
						widget.leftAnchor.absolute = absoluteLeft;
					}
					if(widget.rightAnchor.target==null) {
						widget.rightAnchor.target = t;
						widget.rightAnchor.relative = relativeRight;
						widget.rightAnchor.absolute = absoluteRight;
					}
					if(widget.topAnchor.target == null&&!this.ignoreTopAnchor) {
						widget.topAnchor.target = t;
						widget.topAnchor.relative = relativeTop;
						widget.topAnchor.absolute = absoluteTop;
						
					}
					if(widget.bottomAnchor.target ==null&&!this.ignoreBottomAnchor) {
						widget.bottomAnchor.target = t;
						widget.bottomAnchor.relative = relativeBottom;
						widget.bottomAnchor.absolute = absoluteBottom;
					}
					widget.ResetAndUpdateAnchors();
				}
			} else {
				UIPanel pan = this.GetComponent<UIPanel>();
				if(pan!=null) {
					GameObject go = GameObject.Find(gameObject);
					if(go!=null) {
						Transform t = go.transform;
						pan.leftAnchor.target = t;
						pan.leftAnchor.relative = relativeLeft;
						pan.leftAnchor.absolute = absoluteLeft;
						pan.rightAnchor.target = t;
						pan.rightAnchor.relative = relativeRight;
						pan.rightAnchor.absolute = absoluteRight;
						if(!this.ignoreTopAnchor) {
							pan.topAnchor.target = t;
							pan.topAnchor.relative = relativeTop;
							pan.topAnchor.absolute = absoluteTop;
							
						}
						if(!this.ignoreBottomAnchor) {
							pan.bottomAnchor.target = t;
							pan.bottomAnchor.relative = relativeBottom;
							pan.bottomAnchor.absolute = absoluteBottom;
						}
						pan.ResetAndUpdateAnchors();
					}
				}
			}
		}
	}
}

