// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace cars
{
	[System.Serializable]
	public class CarCoolingPart
	{
		public float heatAddRPMPercent = 0.85f;
		public float maxCoolingSpeed = 60f;
		public float baseCooling = 0.02f;
		public CarCoolingPart ()
		{
		}


	}
}

