// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public enum EDriverMessage
{
	BrakingOnOpponent = 1,
	TiresWorn = 2,
	Overtaking = 3,
	GettingHot = 4,
	Overheating = 5,
	TooHot = 6,
	Damage = 7,
	Avoiding = 8,
}

