// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Racing
{
	public class ErrorState
	{	
		public int framesOfError;
		public float corneringSpeedEffector = 1f;
		public ErrorState (float aHumanError,RacingAI aAI)
		{
			framesOfError = Convert.ToInt32(aHumanError*100);
			
			corneringSpeedEffector = 1000f*UnityEngine.Random.Range(0,aHumanError);
		}
	}
}

