// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public enum ETireWear
{
	Cold = 0,
	Warm = 1,
	Perfect = 2,
	LightWear = 3,
	Worn = 4,
	Dangerous = 5,
}


