// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Racing
{
	[System.Serializable]
	public class SectorTimeTriplet
	{
		public IRDSCarControllerAI car;
		public RacingAI customAI;
		public int lapNumber;
		public float time;
		public string timeString;
		public float totalTime;
		public SectorTimeTriplet (IRDSCarControllerAI aCar,RacingAI aCustomAI)
		{
			car = aCar;
			customAI = aCustomAI;
			lapNumber = aCar.GetLap();
			time = aCar.GetCurrentLapTime();
			timeString = aCar.GetCurrentLapTimeString();
			totalTime = aCar.GetCurrentTotalRaceTime();
		}
	}
}

