// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace Championship
{
	[System.Serializable]
	public class RaceEndFinances
	{
		public int driverACost;
		public int driverABonus;
		public int driverBCost;
		public int driverBBonus;

		public static bool showFinance = false;
		public static RaceEndFinances mostRecent;
		public int date;

		public int prizeA;
		public int prizeB;

		public int damagesA;
		public int damagesB;

		public float sponsorIncome = 0f;
		public RaceEndFinances ()
		{
			
		}
	}
}

